name: Auto Commit

on:
  schedule:
    - cron: '0 */2 * * *'  # Schedule the workflow to run every 2 hours.

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # Action to checkout the repository.

      - name: Set up Git
        run: |
          git config --global user.name 'themuuln'
          # Change this username above  ^^^^^^^^^
          git config --global user.email 'zerone.offical@gmail.com'
          # Change this email above       ^^^^^^^^^^^^^^^^^^^^^^^^
          git config pull.rebase false  # Disable pull rebase to avoid potential conflicts.

      - name: Push Random Empty Commits
        run: |
          cd $GITHUB_WORKSPACE
          branch="main"

          timestamp=$(date '+%Y-%m-%d %H:%M:%S')  # Get the current timestamp.

          git pull origin $branch --ff-only  # Ensure the local branch is up to date with the remote.

          commit_count=$((RANDOM % 4 + 2))  # Generate a random number between 2 to 5 for commit count.

          for ((i=1; i<=commit_count; i++)); do
            commit_message="Automated empty commit $i of $commit_count at $timestamp by themuuln/auto-committer"
            git commit --allow-empty -m "$commit_message"  # Create empty commits with the specified message.
          done

          git push origin $branch  # Push the new empty commits to the remote repository.
